version: "3.7"
services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - ${MYSQL_PORT}:3306
  typeorm-transactions-work:
    build: .
    env_file: .env
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      WAIT_HOSTS: mysql:3306
      WAIT_HOSTS_TIMEOUT: 60
      WAIT_SLEEP_INTERVAL: 5
    depends_on:
      - mysql
    command: sh -c "/wait && yarn jest"
